version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      # - aws cloudformation package --template template.yaml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
      # - aws cloudformation deploy --template-file template-export.yml --s3-bucket $S3_BUCKET --stack-name $STACKNAME --capabilities CAPABILITY_IAM --region $REGION --parameter-overrides Env=$ENV
      - sam build
      - sam package --s3-bucket eyes-sam-package-template-lswn --output-template-file main-package.yaml
      # - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
artifacts:
  discard-paths: true
  files:
    - main-package.yaml
