AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Hello-Sample-Lambda

  Sample SAM Template for Hello-Sample-Lambda
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Parameters:
  Env: # prd: 本番、stg: ステージング、dev: 開発
    Type: String
    AllowedValues:
      - prd
      - stg
      - dev
    Default: dev
  TargetParameter:
    Type: 'String'
    Default: 'foobar'

Resources:
  MainHello:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: 
        !Join
          - ''
          - - 'hello-world'
            - '-'
            - !Ref Env
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          parameter: !Ref TargetParameter
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

